# Generated by Django 4.0.3 on 2022-04-09 05:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('618d0757-161c-4d19-adec-3b555315aaf8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
