# Generated by Django 4.0.3 on 2022-04-09 05:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_alter_instance_id_alter_instance_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'verbose_name': '实例', 'verbose_name_plural': '实例'},
        ),
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0c9777f1-fc22-4ff3-9e0f-e0e9185f983a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AuthCard',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('19636cee-f9c3-4549-b184-12e46b5eb29a'), editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('mac', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.CharField(max_length=200)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapi.instance')),
            ],
        ),
    ]
